name: build

on:
  push:
    branches:
      - main
      - patch-1

jobs:
  build-and-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libx11-dev libxpm-dev libsamplerate0-dev libjack-jackd2-dev lv2-dev

      - name: Configure and build
        run: |
          sed -i 's/USE_NATIVE=1/USE_NATIVE=0/' src/Makefile
          sed -i 's/USE_ARM=0/USE_ARM=0/' src/Makefile
          sed -i 's/USE_LV2=1/USE_LV2=1/' src/Makefile
          sed -i 's/USE_GTKMM=0/USE_GTKMM=0/' src/Makefile
          cd src && make && make install

      - name: Create zip file
        run: |
          zip -r vdx7.zip ~/.local/bin/vdx7 ~/.config/vdx7/vdx7.ram ~/.lv2/vdx7.lv2/vdx7.so ~/.lv2/vdx7.lv2/vdx7.ttl ~/.lv2/vdx7.lv2/manifest.ttl ~/.lv2/vdx7.lv2/vdx7.ram

      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TITLE: "Release ${{ github.sha }}"
          RELEASE_NOTES: "Automated release"
        with:
          tag_name: "v${{ github.sha }}"
          draft: false
          prerelease: false

      - name: Upload release asset to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./vdx7.zip
          asset_name: vdx7.zip
          asset_content_type: application/zip
